コメント機能実装
goruchanchan/fjord-books_app pull request #6
Opened 2022-09-14 14:03 UTC by goruchanchan

ご確認よろしくお願いします。

2022-09-18 14:42 UTC, u1tnk requested changes

2022-09-18 14:42 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +      if @comment.save
`save`を使うときは必ずelseを付けてvalidation error時の処理を書きましょう。
もし、基本的にエラーにならないはずの場所であれば `save!`を使うと良いです。例外になるので異常が検知できるので。

2022-09-18 14:42 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +      if @comment.update(content: params[:content])
saveと同様です。

2022-09-18 14:42 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +        format.json { render :show, status: :created, location: @comment }
jsonの方は書いていても良いですが、本プラクティスでは使わないので無くても良いです。

2022-09-18 14:42 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +    @comment.destroy
ここは前述した `save!`と同じ理由で`destory!`ですね。

2022-09-18 14:42 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +  before_action :create_comment, only: %i[create]
一箇所だけでしか使わない `create`メソッドのメインの処理を before_actionに書くのは良くないです。

2022-09-18 14:42 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +    @comment = if request.path.match?(%r{/reports/})
`@commentable`が入っていれば共通化できると思います。

2022-09-18 14:42 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +    @commentable = if request.path.match?(%r{/reports/})
`request.path.match?(%r{/reports/})`
こういう何回も出てくるのでメソッド化した方が良いと思います。

2022-09-20 14:16 UTC, goruchanchan commented on app/controllers/comments_controller.rb
> +      if @comment.save
`save` と `save!` メソッドの違いを理解していなかったので勉強になりました！ありがとうございます！（そもそも `save` についても理解が怪しかったので、とても参考になりました😅）

2022-09-21 00:59 UTC, u1tnk approved these changes
🙆‍♀️ 

`select_commentable_or_path` は冗長では無いし、合格とします。
ただ、 戻り値の性質すら引数によって変わるのがちょっと分かりづらいかなとは思いました。
他の合格例を見てこの問題をどのように解決してるかだけ確認しておいてください。

2022-10-01 13:01 UTC, merged